# Generated by Django 4.0.4 on 2022-05-28 02:49

from django.db import migrations, models
import laser.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('modify', models.DateField(auto_now=True, verbose_name='Update')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(max_length=255, verbose_name='Description')),
                ('type', models.CharField(choices=[('mark', 'mark'), ('cut', 'cut'), ('clean', 'clean'), ('weld', 'weld')], max_length=20, verbose_name='Type')),
                ('file_upload', models.FileField(upload_to=laser.models.get_file_path, verbose_name='File')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
