# Generated by Django 4.0.4 on 2022-05-28 02:56

from django.db import migrations, models
import django.db.models.deletion
import laser.models


class Migration(migrations.Migration):

    dependencies = [
        ('laser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('modify', models.DateField(auto_now=True, verbose_name='Update')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(max_length=255, verbose_name='Description')),
                ('file_upload', models.FileField(upload_to=laser.models.get_file_path, verbose_name='File')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laser.manual', verbose_name='Type')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
