# Generated by Django 4.0.4 on 2022-05-28 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laser', '0002_software'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='type',
            field=models.CharField(choices=[('mark', 'mark'), ('cut', 'cut'), ('clean', 'clean'), ('weld', 'weld')], max_length=20, verbose_name='Type'),
        ),
    ]
