# Generated by Django 4.0.4 on 2022-05-28 12:31

from django.db import migrations, models
import laser.models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('laser', '0003_alter_software_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('modify', models.DateField(auto_now=True, verbose_name='Update')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(max_length=255, verbose_name='Description')),
                ('type', models.CharField(choices=[('mark', 'mark'), ('cut', 'cut'), ('clean', 'clean'), ('weld', 'weld')], max_length=20, verbose_name='Type')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price')),
                ('image', stdimage.models.StdImageField(force_min_size=False, upload_to=laser.models.get_file_path, variations={'thumb': {'crop': True, 'height': 180, 'width': 286}}, verbose_name='Image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('modify', models.DateField(auto_now=True, verbose_name='Update')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(max_length=255, verbose_name='Description')),
                ('type', models.CharField(choices=[('mark', 'mark'), ('cut', 'cut'), ('clean', 'clean'), ('weld', 'weld')], max_length=20, verbose_name='Type')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price')),
                ('image', stdimage.models.StdImageField(force_min_size=False, upload_to=laser.models.get_file_path, variations={'thumb': {'crop': True, 'height': 180, 'width': 286}}, verbose_name='Image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
