# Generated by Django 4.0.4 on 2022-05-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laser', '0004_equipment_sparepart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manual',
            name='type',
            field=models.CharField(choices=[('Mark', 'Mark'), ('Cut', 'cut'), ('Clean', 'clean'), ('Weld', 'weld')], max_length=20, verbose_name='Type'),
        ),
    ]
