# Generated by Django 4.0.4 on 2022-05-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laser', '0005_alter_manual_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(choices=[('Mark', 'Mark'), ('Cut', 'Cut'), ('Clean', 'Clean'), ('Weld', 'Weld')], max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='manual',
            name='type',
            field=models.CharField(choices=[('Mark', 'Mark'), ('Cut', 'Cut'), ('Clean', 'Clean'), ('Weld', 'Weld')], max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='software',
            name='type',
            field=models.CharField(choices=[('Mark', 'Mark'), ('Cut', 'Cut'), ('Clean', 'Clean'), ('Weld', 'Weld')], max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='type',
            field=models.CharField(choices=[('Mark', 'Mark'), ('Cut', 'Cut'), ('Clean', 'Clean'), ('Weld', 'Weld')], max_length=20, verbose_name='Type'),
        ),
    ]
