# Generated by Django 4.0.4 on 2022-05-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laser', '0006_alter_equipment_type_alter_manual_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manual',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='software',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
    ]
